# Generated by Django 2.2.4 on 2019-10-18 11:36

from django.db import migrations, models
import django.db.models.deletion
import mhd.utils.uuid
import mhd_data.fields.json


class Migration(migrations.Migration):

    replaces = [('mhd_provenance', '0001_initial'), ('mhd_provenance', '0002_auto_20190819_0754'), ('mhd_provenance', '0003_auto_20191018_1136')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.UUIDField(default=mhd.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Time at which this provenance was created')),
                ('predecessor', models.ForeignKey(blank=True, help_text='Previous provenance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mhd_provenance.Provenance')),
                ('metadata', mhd_data.fields.json.SmartJSONField(blank=True, help_text='Metadata associated with this object', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
