# Generated by Django 2.2.4 on 2019-10-18 11:36

from django.db import migrations, models
import mhd.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_provenance', '0002_auto_20190819_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenance',
            name='id',
            field=models.UUIDField(default=mhd.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
