# Generated by Django 2.2.4 on 2019-10-24 10:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='graphassparse6',
            name='mhd_data_gr_item_id_da3b10_idx',
        ),
        migrations.RemoveIndex(
            model_name='listasarray_standardint',
            name='mhd_data_li_item_id_ab9e25_idx',
        ),
        migrations.RemoveIndex(
            model_name='listasarray_standardjson',
            name='mhd_data_li_item_id_2767c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='matrixaslist_standardint_2_2',
            name='mhd_data_ma_item_id_0038fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='matrixaslist_standardint_3_3',
            name='mhd_data_ma_item_id_f852f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='polynomialassparsearray',
            name='mhd_data_po_item_id_09c341_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardbool',
            name='mhd_data_st_item_id_bb66ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardint',
            name='mhd_data_st_item_id_253a32_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardjson',
            name='mhd_data_st_item_id_2c1d86_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardstring',
            name='mhd_data_st_item_id_4d9502_idx',
        ),
        migrations.AddIndex(
            model_name='graphassparse6',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_gr_item_id_1aa7ff_hash'),
        ),
        migrations.AddIndex(
            model_name='listasarray_standardint',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_li_item_id_9e0206_hash'),
        ),
        migrations.AddIndex(
            model_name='listasarray_standardjson',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_li_item_id_26eb9e_hash'),
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_2_2',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_ma_item_id_064e4a_hash'),
        ),
        migrations.AddIndex(
            model_name='matrixaslist_standardint_3_3',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_ma_item_id_910fdf_hash'),
        ),
        migrations.AddIndex(
            model_name='polynomialassparsearray',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_po_item_id_0c1a41_hash'),
        ),
        migrations.AddIndex(
            model_name='standardbool',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_st_item_id_184ce3_hash'),
        ),
        migrations.AddIndex(
            model_name='standardint',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_st_item_id_5f1dbc_hash'),
        ),
        migrations.AddIndex(
            model_name='standardjson',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_st_item_id_5c9dfd_hash'),
        ),
        migrations.AddIndex(
            model_name='standardstring',
            index=django.contrib.postgres.indexes.HashIndex(fields=['item'], name='mhd_data_st_item_id_dba3ba_hash'),
        ),
    ]
