# Generated by Django 3.2.12 on 2022-04-23 15:24

from django.db import migrations, models
import mhd_data.fields.ndarray


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_data', '0003_auto_20220422_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listasarray_standardjson',
            name='value',
            field=mhd_data.fields.ndarray.SmartNDArrayField(blank=True, dim=1, null=True, size=None, typ=models.JSONField()),
        ),
        migrations.AlterField(
            model_name='standardjson',
            name='value',
            field=models.JSONField(),
        ),
    ]
