# Generated by Django 2.2.4 on 2019-10-14 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0003_auto_20190821_0751'),
        ('mhd_data', '0010_auto_20191010_1419'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ItemCollectionAssociation',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Collection')),
                    ],
                    options={
                        'db_table': 'mhd_data_item_collections',
                    },
                ),
                migrations.AlterField(
                    model_name='item',
                    name='collections',
                    field=models.ManyToManyField(blank=True, help_text='Collection(s) each item occurs in', through='mhd_data.ItemCollectionAssociation', to='mhd_schema.Collection'),
                ),
                migrations.AddField(
                    model_name='itemcollectionassociation',
                    name='item',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhd_data.Item'),
                ),
                migrations.AlterUniqueTogether(
                    name='itemcollectionassociation',
                    unique_together={('item', 'collection')},
                ),
            ],
            database_operations=[]
        ),
    ]
