# Generated by Django 2.2.4 on 2019-10-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_data', '0011_auto_20191014_1920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemcollectionassociation',
            table=None,
        ),
    ]
