# Generated by Django 2.2.4 on 2019-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodecCatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='MDDL name', null=True, unique=True)),
                ('math_type', models.TextField(blank=True, help_text='MMT Term representing mathtype', null=True)),
                ('db_type', models.TextField(blank=True, help_text='MMT Term representing dbtype', null=True)),
                ('kind', models.CharField(blank=True, choices=[('Codec', 'Codec'), ('Codec Operator', 'Codec Operator'), ('Import only', 'Import only'), ('Export only', 'Export only')], help_text='Kind of codec', max_length=256, null=True)),
                ('description', models.TextField(blank=True, help_text='Human readable description', null=True)),
                ('comment', models.TextField(blank=True, help_text='Extra comment', null=True)),
                ('implemented', models.BooleanField(help_text='Implementation Status')),
                ('mddl', models.BooleanField(help_text='Status in MDDL')),
            ],
        ),
    ]
