# Generated by Django 2.2.4 on 2019-08-17 13:55

from django.db import migrations, models
import mdh_data.fields.ndarray


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumbNDArrayOneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', mdh_data.fields.ndarray.DumbNDArrayField(dim=1, typ=models.IntegerField())),
            ],
        ),
        migrations.CreateModel(
            name='DumbNDArrayTwoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', mdh_data.fields.ndarray.DumbNDArrayField(dim=2, typ=models.IntegerField())),
            ],
        ),
        migrations.CreateModel(
            name='SmartNDArrayOneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', mdh_data.fields.ndarray.SmartNDArrayField(dim=1, typ=models.IntegerField())),
            ],
        ),
        migrations.CreateModel(
            name='SmartNDArrayTwoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', mdh_data.fields.ndarray.SmartNDArrayField(dim=2, typ=models.IntegerField())),
            ],
        ),
    ]
