# Generated by Django 2.2.10 on 2020-03-23 12:38

from django.db import migrations, models
import mviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='The database name of this view', unique=True)),
                ('sql', models.TextField(help_text='The SQL of this view')),
                ('paramsJSON', models.TextField(help_text='The parameters of this view')),
                ('materialized', models.BooleanField(help_text='Boolean indicating if this view is materialized')),
            ],
            bases=(mviews.models.ViewImplementation, models.Model),
        ),
    ]
