# Generated by Django 2.2.4 on 2019-08-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_schema', '0002_auto_20190819_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default='No description provided', help_text='A human-readable description of this collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='url',
            field=models.URLField(blank=True, help_text='URL for more information about this collection', null=True),
        ),
    ]
