# Generated by Django 2.2.4 on 2019-09-09 15:30

from django.db import migrations, models
import django.db.models.deletion
import mdh.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_provenance', '0002_auto_20190819_0754'),
        ('mhd_schema', '0003_auto_20190821_0751'),
        ('mdh_data', '0007_listasarray_standardjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphAsSparse6',
            fields=[
                ('id', models.UUIDField(default=mdh.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', models.TextField()),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mdh_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mhd_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdh_data.GraphAsSparse6')),
            ],
            options={
                'abstract': False,
                'unique_together': {('item', 'prop', 'superseeded_by')},
            },
        ),
    ]
