# Generated by Django 2.2.4 on 2019-10-10 14:19

from django.db import migrations, models
import mdh_data.fields.json
import mdh_data.fields.ndarray


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_data', '0009_standardstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listasarray_standardint',
            name='value',
            field=mdh_data.fields.ndarray.SmartNDArrayField(blank=True, dim=1, null=True, size=None, typ=models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='listasarray_standardjson',
            name='value',
            field=mdh_data.fields.ndarray.SmartNDArrayField(blank=True, dim=1, null=True, size=None, typ=mdh_data.fields.json.SmartJSONField()),
        ),
    ]
