# Generated by Django 2.2.4 on 2019-10-18 14:50

from django.db import migrations, models
import django.db.models.deletion
import mhd_data.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', mhd_data.fields.json.SmartJSONField(blank=True, help_text='Metadata associated with this object', null=True)),
                ('displayName', models.TextField(help_text='Name of this collection')),
                ('slug', models.SlugField(help_text='Identifier of this collection', unique=True)),
                ('description', models.TextField(help_text='A human-readable description of this collection')),
                ('url', models.URLField(blank=True, help_text='URL for more information about this collection', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', mhd_data.fields.json.SmartJSONField(blank=True, help_text='Metadata associated with this object', null=True)),
                ('displayName', models.TextField(help_text='Display Name for this property')),
                ('slug', models.SlugField(help_text='Identifier of this Collection')),
                ('codec', models.SlugField(help_text='Name of the codec table that stores this property ')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCollectionMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Collection')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Collection(s) this property occurs in', through='mhd_schema.PropertyCollectionMembership', to='mhd_schema.Collection'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='mhd_schema__slug_757907_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycollectionmembership',
            index=models.Index(fields=['property'], name='mhd_schema__propert_fdce0b_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycollectionmembership',
            index=models.Index(fields=['collection'], name='mhd_schema__collect_62762f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertycollectionmembership',
            unique_together={('property', 'collection')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='mhd_schema__slug_bc8f20_idx'),
        ),
    ]
