# Generated by Django 2.2.4 on 2019-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='flag_large_collection',
            field=models.BooleanField(default=False, help_text='Flag this collection as potentially large to the user interface'),
        ),
    ]
