# Generated by Django 2.2.4 on 2019-10-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0003_auto_20190821_0751'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PropertyCollectionMembership',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Collection')),
                    ],
                    options={
                        'db_table': 'mhd_schema_property_collections',
                    },
                ),
                migrations.AlterField(
                    model_name='property',
                    name='collections',
                    field=models.ManyToManyField(blank=True, help_text='Collection(s) this property occurs in', through='mhd_schema.PropertyCollectionMembership', to='mhd_schema.Collection'),
                ),
                migrations.AddField(
                    model_name='propertycollectionmembership',
                    name='property',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Property'),
                ),
                migrations.AlterUniqueTogether(
                    name='propertycollectionmembership',
                    unique_together={('property', 'collection')},
                ),
            ],
            database_operations=[]
        ),
    ]
