# Generated by Django 2.2.4 on 2019-10-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0003_auto_20191027_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='Description of this pre-filter')),
                ('condition', models.TextField(default='', help_text='Condition of this pre-filter')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Collection')),
            ],
        ),
    ]
