# Generated by Django 2.2.4 on 2019-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0004_prefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='count',
            field=models.IntegerField(blank=True, help_text='Total number of items in this collection', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='count_frozen',
            field=models.BooleanField(default=False, help_text='When set to true, freeze the count of this collection'),
        ),
    ]
