# Generated by Django 2.2.4 on 2019-10-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0004_auto_20191014_2002'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertycollectionmembership',
            table=None,
        ),
    ]
