# Generated by Django 2.2.4 on 2019-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0005_auto_20191028_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefilter',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
