# Generated by Django 2.2.4 on 2019-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0005_auto_20191014_2005'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='mhd_schema__slug_757907_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='mhd_schema__slug_bc8f20_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycollectionmembership',
            index=models.Index(fields=['property'], name='mhd_schema__propert_fdce0b_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycollectionmembership',
            index=models.Index(fields=['collection'], name='mhd_schema__collect_62762f_idx'),
        ),
    ]
