# Generated by Django 2.2.4 on 2019-10-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0006_auto_20191014_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id']},
        ),
    ]
