# Generated by Django 2.2.10 on 2020-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0006_prefilter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='materializedViewName',
            field=models.SlugField(blank=True, help_text='Name for the materialized view of this collection (if any)', null=True, unique=True),
        ),
    ]
