# Generated by Django 2.2.10 on 2020-03-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0007_collection_materializedviewname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='materializedViewName',
            new_name='viewName',
        ),
        migrations.AlterField(
            model_name='collection',
            name='viewName',
            field=models.SlugField(blank=True, help_text='Name for the (potentially materialized) view of this collection (if any)', null=True, unique=True),
        ),
    ]
