# Generated by Django 3.0.14 on 2022-03-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0008_auto_20200323_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id'], 'verbose_name_plural': 'Properties'},
        ),
    ]
