# Generated by Django 3.2.12 on 2022-04-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0009_auto_20220323_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='template',
            field=models.TextField(blank=True, default=None, help_text='Custom template for rendering this collection', null=True),
        ),
    ]
