# Generated by Django 3.2.14 on 2022-09-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0012_auto_20220423_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide the collection from the home page'),
        ),
    ]
