# Generated by Django 3.2.14 on 2022-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0013_collection_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default',
            field=models.BooleanField(default=True, help_text='Show property by default in frontend interface'),
        ),
    ]
