# Generated by Django 3.2.14 on 2022-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_schema', '0014_property_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='exporters',
            field=models.ManyToManyField(blank=True, help_text='List of enabled exporters for this collection', to='mhd_schema.Exporter'),
        ),
    ]
